// 34 đơn vị hành chính cấp tỉnh theo NQ 202/2025/QH15 (hiệu lực 1/7/2025).
// Cập nhật: Quảng Ninh thành TP trực thuộc TW (NQ 36/2026/QH16, từ 1/9/2026); Bắc Ninh (NQ 39/2026/QH16, từ 20/9/2026).
// Danh sách tỉnh cũ: vietnam-briefing.com/news/vietnams-government-introduces-official-plan-for-provincial-mergers.html
window.PROVINCES = [
  { id: 'hanoi', name: 'Hà Nội', city: 1, r: 'Bắc', old: [] },
  { id: 'caobang', name: 'Cao Bằng', r: 'Bắc', old: [] },
  { id: 'tuyenquang', name: 'Tuyên Quang', r: 'Bắc', old: ['Tuyên Quang', 'Hà Giang'] },
  { id: 'laocai', name: 'Lào Cai', r: 'Bắc', old: ['Lào Cai', 'Yên Bái'] },
  { id: 'dienbien', name: 'Điện Biên', r: 'Bắc', old: [] },
  { id: 'laichau', name: 'Lai Châu', r: 'Bắc', old: [] },
  { id: 'sonla', name: 'Sơn La', r: 'Bắc', old: [] },
  { id: 'thainguyen', name: 'Thái Nguyên', r: 'Bắc', old: ['Thái Nguyên', 'Bắc Kạn'] },
  { id: 'langson', name: 'Lạng Sơn', r: 'Bắc', old: [] },
  { id: 'quangninh', name: 'Quảng Ninh', city: 1, cityNote: 'TP trực thuộc TW từ 1/9/2026 (NQ 36/2026/QH16)', r: 'Bắc', old: [] },
  { id: 'phutho', name: 'Phú Thọ', r: 'Bắc', old: ['Phú Thọ', 'Vĩnh Phúc', 'Hoà Bình'] },
  { id: 'bacninh', name: 'Bắc Ninh', city: 1, cityNote: 'TP trực thuộc TW từ 20/9/2026 (NQ 39/2026/QH16)', r: 'Bắc', old: ['Bắc Ninh', 'Bắc Giang'] },
  { id: 'haiphong', name: 'Hải Phòng', city: 1, r: 'Bắc', old: ['Hải Phòng', 'Hải Dương'] },
  { id: 'hungyen', name: 'Hưng Yên', r: 'Bắc', old: ['Hưng Yên', 'Thái Bình'] },
  { id: 'ninhbinh', name: 'Ninh Bình', r: 'Bắc', old: ['Ninh Bình', 'Nam Định', 'Hà Nam'] },
  { id: 'thanhhoa', name: 'Thanh Hoá', r: 'Trung', old: [] },
  { id: 'nghean', name: 'Nghệ An', r: 'Trung', old: [] },
  { id: 'hatinh', name: 'Hà Tĩnh', r: 'Trung', old: [] },
  { id: 'quangtri', name: 'Quảng Trị', r: 'Trung', old: ['Quảng Trị', 'Quảng Bình'] },
  { id: 'hue', name: 'Huế', city: 1, r: 'Trung', old: [] },
  { id: 'danang', name: 'Đà Nẵng', city: 1, r: 'Trung', old: ['Đà Nẵng', 'Quảng Nam'], extra: 'Bao gồm quần đảo Hoàng Sa' },
  { id: 'quangngai', name: 'Quảng Ngãi', r: 'Trung', old: ['Quảng Ngãi', 'Kon Tum'] },
  { id: 'gialai', name: 'Gia Lai', r: 'Trung', old: ['Gia Lai', 'Bình Định'] },
  { id: 'daklak', name: 'Đắk Lắk', r: 'Trung', old: ['Đắk Lắk', 'Phú Yên'] },
  { id: 'khanhhoa', name: 'Khánh Hoà', r: 'Trung', old: ['Khánh Hoà', 'Ninh Thuận'], extra: 'Bao gồm quần đảo Trường Sa' },
  { id: 'lamdong', name: 'Lâm Đồng', r: 'Trung', old: ['Lâm Đồng', 'Đắk Nông', 'Bình Thuận'] },
  { id: 'hcm', name: 'TP. Hồ Chí Minh', city: 1, r: 'Nam', old: ['TP. Hồ Chí Minh', 'Bình Dương', 'Bà Rịa – Vũng Tàu'] },
  { id: 'dongnai', name: 'Đồng Nai', r: 'Nam', old: ['Đồng Nai', 'Bình Phước'] },
  { id: 'tayninh', name: 'Tây Ninh', r: 'Nam', old: ['Tây Ninh', 'Long An'] },
  { id: 'vinhlong', name: 'Vĩnh Long', r: 'Nam', old: ['Vĩnh Long', 'Bến Tre', 'Trà Vinh'] },
  { id: 'dongthap', name: 'Đồng Tháp', r: 'Nam', old: ['Đồng Tháp', 'Tiền Giang'] },
  { id: 'cantho', name: 'Cần Thơ', city: 1, r: 'Nam', old: ['Cần Thơ', 'Sóc Trăng', 'Hậu Giang'] },
  { id: 'angiang', name: 'An Giang', r: 'Nam', old: ['An Giang', 'Kiên Giang'] },
  { id: 'camau', name: 'Cà Mau', r: 'Nam', old: ['Cà Mau', 'Bạc Liêu'] },
];
